### ISSUE TITLE
Private key is empty

### ISSUE THREAD

**Issue by rahxam** [yazdan/openwrt-surfshark-wireguard#1]
Hey,
I ran the script and it generated the files, but there is no private key.

Any ideas what I am doing wrong?

**Comment by yazdan** [comment]
Hmm, can you check to if `wg.json` has private key in it?

If no I think you need to install/have `wg`, because this is used to generate private and publickey

**Comment by rahxam** [comment]
Hi,
I just ran the script some more times and it worked now. I also got multiple times an error 400.

Thanks for your effort.
