### ISSUE TITLE
Not an issue more of trying to understand

### ISSUE THREAD

**Issue by yarafie** [yazdan/openwrt-surfshark-wireguard#6]
I am curious why is the peer with wgs.prod.surfshark.com needed?

**Comment by yazdan** [comment]
I don't have any clue like you.

What I've done is implementing PHP/Python/JS repositories that I've found on Github to bash
So it was there

https://github.com/Incognito-Coder/Wiregen
https://github.com/jcreigh/pysurfshark
https://github.com/cardimajs/surfshark-wireguard
